Update docs.md
mautic/mautic-community-handbook pull request #187
Opened 2024-02-17 09:22 UTC by domidc

New names in the council added

2024-02-25 05:47 UTC, RCheesley requested changes
I have updated the list to include Mautic emails rather than professional emails, and also to correct a few inaccuracies with job titles.

2024-02-25 05:47 UTC, RCheesley commented on pages/04.community-leadership/03.community-council/docs.md
> +| Andy Towne | Senior customer value manager at Acquia | https://linkedin.com/in/andytowne            |
```suggestion
| Andy Towne | Senior Customer Value Manager at Acquia | andy.towne@mautic.org           | 
```

2024-02-25 05:47 UTC, RCheesley commented on pages/04.community-leadership/03.community-council/docs.md
> +| Dominique De Cooman | Dropsolid Co-founder and co-CEO | dominique@dropsolid.com            |
```suggestion
| Dominique De Cooman | Dropsolid Co-founder and co-CEO | dominique.decooman@mautic.org           | 
```

2024-02-25 05:47 UTC, RCheesley commented on pages/04.community-leadership/03.community-council/docs.md
>  | John Linhart | Technical Community Lead at Acquia | jan.linhart@acquia.com           |
```suggestion
| John Linhart | Principal Software Engineer at Acquia | john.linhart@mautic.org           |
```

2024-02-25 05:47 UTC, RCheesley commented on pages/04.community-leadership/03.community-council/docs.md
> +| Favour Chibueze  | Community Representative | favour.kelvin@mautic.org             |
```suggestion
| Favour Chibueze  | Front End Engineer at Eden Life Inc. | favour.chibueze@mautic.org             | 
```

2024-02-25 05:47 UTC, RCheesley commented on pages/04.community-leadership/03.community-council/docs.md
> +| Norman Pracht  | CEO Webmecanik | 	norman.pracht@mautic.org            |
```suggestion
| Norman Pracht  | Associate General Manager, Webmecanik | 	norman.pracht@mautic.org            | 
```

2024-02-25 05:47 UTC, RCheesley commented on pages/04.community-leadership/03.community-council/docs.md
> +| Prateek Jain | Director of digital experience services at Axelerant | prateek@axelerant.com            |
```suggestion
| Prateek Jain | Director of Digital Experience Services at Axelerant | prateek.jain@mautic.org           | 
```

2024-03-22 14:09 UTC, domidc reviewed
Reviewed

2024-03-27 16:50 UTC, npracht approved these changes

2024-03-27 16:52 UTC, merged

2024-03-27 16:53 UTC, RCheesley commented
@all-contributors please add @domidc for docs