Added Community-to-RST #223
mautic/mautic-community-handbook pull request #237
Opened 2024-10-16 18:18 UTC by HappySR

1. Deleted the .rev files from the community-team section.
2. Copied the community-team to docs/ and then converted the .md files to .rst files.
3. Updated the index.rst

2024-10-19 17:56 UTC, HappySR commented
Created a PR named Added Community-to-RST #223 kindly review it

2024-10-22 02:27 UTC, RCheesley requested changes
Hi @HappySR thanks for making a start!

It looks like maybe you ran this file through a converter because there were a bunch of things not implemented correctly which are clearly documented in the issue like how to do headings and links.  Please take a look in the future, as it takes us time to write those guidance notes ;) 

I've fixed most of the fundamental issues like moving the files into the right place, creating the link files which were missing (you'd used inline links, which we don't use), and also fixing some of the heading structure which was using all kinds of heading levels and was completely missing in some places causing the RST checker to fail to build.

The PR should now build correctly but I have left you some Vale fixes to address before we can consider the PR for merging.

Sorry again for the delay, we've been a little swamped with contributions which means it's taken time to fix a couple of bugs with our Q/A pipeline and get these PRs reviewed. 

Hopefully once these are fixed it'll be quick to merge! 🚀

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +The Community Dashboard uses the open-source :xref:`Savannah CRM` tool to import, analyze and visualize data from multiple sources in one central location.
```suggestion
The Community Dashboard uses the open source :xref:`Savannah CRM` tool to import, analyze, and visualize data from multiple sources in one central location.
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +Currently the dashboad imports:
```suggestion
Currently the dashboard imports:
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +-  All repositories listed under github.com/mautic
```suggestion
-  All repositories listed under ``github.com/mautic``
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +-  Specified channels from mautic.slack.com
```suggestion
-  Specified channels from ``mautic.slack.com``
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +-  All threads on forums.mautic.org
```suggestion
-  All threads on ``forum.mautic.org``
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +-  All threads on reddit.com/r/mautic
```suggestion
-  All threads on ``reddit.com/r/mautic``
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +-  Specified meetup.com groups (coming soon)
```suggestion
```

This is no longer relevant (we don't use meetup.com any more) so I would remove this line al together.

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_dashboard.rst
> +The information is used to determine the activity levels of individuals and organizaitons within the community, which informs the monthly updates in Slack and the ranking of organizations in the :xre
```suggestion
Mautic uses this information to determine the activity levels of individuals and organizations within the community, which informs the monthly updates in Slack and the ranking of organizations in the :xref:`Partners' Directory`.
```

2024-10-22 02:27 UTC, RCheesley commented on docs/teams/community_team/community_team.rst
> +-  As ambassadors: People in different countries who are already well-connected through other activities, and have a broad understanding of Mautic's facets (both from the user's and from the MarTech
```suggestion
-  As ambassadors: People in different countries who are already well-connected through other activities, and have a broad understanding of Mautic's facets (both from the user's and from the MarTech and even developer side, but no actual developer knowledge required)
```

2025-02-01 18:03 UTC, favour-chibueze commented
fix 
```diff
diff --git a/docs/teams/community_team/community_dashboard.rst b/docs/teams/community_team/community_dashboard.rst
index 1d715b3e..efe00d79 100644
--- a/docs/teams/community_team/community_dashboard.rst
+++ b/docs/teams/community_team/community_dashboard.rst
@@ -1,17 +1,17 @@
 Community dashboard
 ###################
 
-The Community Dashboard uses the open-source :xref:`Savannah CRM` tool to import, analyze and visualize data from multiple sources in one central location.
+The Community Dashboard uses the open source :xref:`Savannah CRM` tool to import, analyze, and visualize data from multiple sources in one central location.  
+
 
 You can view the data from the last 90 days on the :xref:`Savannah Dashboard`.
 
-Currently the dashboad imports:
+Currently the dashboard imports:
 
--  All repositories listed under github.com/mautic
--  Specified channels from mautic.slack.com
--  All threads on forums.mautic.org
--  All threads on reddit.com/r/mautic
+-  All repositories listed under ``github.com/mautic`` 
+-  Specified channels from ``mautic.slack.com`` 
+-  All threads on ``forum.mautic.org``  
+-  All threads on ``reddit.com/r/mautic`` 
 -  All Stack Overflow posts tagged with Mautic
--  Specified meetup.com groups (coming soon)
 
-The information is used to determine the activity levels of individuals and organizaitons within the community, which informs the monthly updates in Slack and the ranking of organizations in the :xref:`Partners' Directory`.
+Mautic uses this information to determine the activity levels of individuals and organizations within the community, which informs the monthly updates in Slack and the ranking of organizations in the :xref:`Partners' Directory`.
\ No newline at end of file
diff --git a/docs/teams/community_team/community_team.rst b/docs/teams/community_team/community_team.rst
index 21a0821d..3bed7bc7 100644
--- a/docs/teams/community_team/community_team.rst
+++ b/docs/teams/community_team/community_team.rst
@@ -3,9 +3,10 @@ Community Team
 
 Mission and expectations
 ************************
+   ::
 
-   We want more and more people to feel at home in the Mautic community.
-   And we want to inspire & enable them to contribute to our cause.
+      We want more and more people to feel at home in the Mautic community.
+      And we want to inspire & enable them to contribute to our cause.
 
 General Community Team tasks
 ****************************
@@ -31,8 +32,7 @@ General activities of the Community Team
 But also
 
 -  Understand community personas
--  Promote and help building a business on Mautic, and explain active
-   contribution as an important element of it
+-  Promote and help building a business on Mautic, and explain active contribution as an important element of it
 -  Find, grow and support ambassadors
 -  Connect & collaborate with other communities
 -  Support fundraising initiatives
@@ -40,8 +40,7 @@ But also
 Global Communities
 ==================
 
--  Make global community more accessible, give transparency on
-   tasks/actors/processes, and provide easy starting points
+-  Make global community more accessible, give transparency on tasks/actors/processes, and provide easy starting points
 -  Reach out to previously active contributors, try to reactivate them
    Including: WHAT is the message? WHAT are the channels?
 -  Reach out to existing passive community members, try to activate them
@@ -62,7 +61,7 @@ Profiles of contributors needed in the Community Team
 *****************************************************
 
 -  Everyone who is enthusiastic enough
--  As ambassadors: People in different countries who are already well-connected through other activities, and have a broad understanding of Mautic's facets (both from the user's and from the MarTech and even dev side, but no actual dev knowledge required)
+-  As ambassadors: People in different countries who are already well-connected through other activities, and have a broad understanding of Mautic's facets (both from the user's and from the MarTech and even developer side, but no actual developer knowledge required)
 -  Define what we call people who start or lead a community in a certain
    country
 

```

2025-02-02 09:36 UTC, RCheesley requested changes
Some fixes for the Vale errors. Not RTC until these are resolved.

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/community_team.rst
> +-  Is interested in Mautic, even without ever contributing!
```suggestion
-  Is interested in Mautic, even without ever contributing
```

Vale fix

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/community_team.rst
> +**Would you like to be involved in this team? Join :xref:`Community Team Slack` on Slack!**
```suggestion
**Would you like to be involved in this team? Join :xref:`Community Team Slack` on Slack**
```

Vale fix

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +Guidance for establishing official Mautic Meetups, Groups & Events
```suggestion
Guidance for establishing official Mautic meetups, groups & events
```

Vale fix

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +The Community Team agreed on 12th December 2019 the following guidelines
```suggestion
The Community Team agreed on 12/12/2019 the following guidelines
```

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +All meetups, groups and events agree to abide by the Mautic :xref:`CoC` at all times.
```suggestion
All meetups, groups, and events agree to abide by the Mautic :xref:`CoC` at all times.
```
Vale fix

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +Mautic Meetups
```suggestion
Mautic meetups
```

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +These are the traditional kind of in-person meetups which are based in a
```suggestion
These are the traditional kind of in-person meetups, based in a
```

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +region or a town. They are **not** to be created on a country-wide
```suggestion
region or a town. They're **not** created on a country-wide
```

2025-02-02 09:36 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +Official groups will have a Meetup group created on the :xref:`Community Portal` and a category created in :xref:`Meetups Forum Category` on the forums once the following criteria are met:
```suggestion
Official groups have a Meetup group created on the :xref:`Community Portal` and a category created in :xref:`Meetups Forum Category` on the forums once the following criteria are met: 
```

2025-02-02 09:41 UTC, RCheesley requested changes
More fixes

2025-02-02 09:41 UTC, RCheesley commented on docs/teams/community_team/community_team.rst
> +Global Communities
```suggestion
Global communities
```

2025-02-02 09:41 UTC, RCheesley commented on docs/teams/community_team/community_team.rst
> +   Including: WHAT is the message? WHAT are the channels?
```suggestion
   Including: what is the message? What are the channels?
```

2025-02-02 09:41 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +The Community Team agreed on 12/12/2019 the following guidelines
```suggestion
The Community Team agreed on December 12, 2019 the following guidelines
```

2025-02-02 09:41 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +4. A location confirmed for meeting which is an office or community space (i.e. not a bar/pub)
```suggestion
4. A location confirmed for meeting which is an office or community space (not a bar/pub)
```

2025-02-02 09:41 UTC, RCheesley commented on docs/teams/community_team/meetup_guidelines.rst
> +6. A proposed time and day each month (e.g. from 6pm on the first Friday of each month) for regular events
```suggestion
6. A proposed time and day each month (for example from 6 PM on the first Friday of each month) for regular events
```

2025-02-02 09:43 UTC, RCheesley commented on docs/teams/community_team/community_team.rst
> +   Including: what is the message? What are the channels?
```suggestion
   Including: what's the message? What are the channels?
```

2025-02-28 15:47 UTC, RCheesley submitted a review, later dismissed
Just made a commit to fix the outstanding issues.

Please always render the docs locally to make sure that you're picking up possible issues like this one:

![Community-Team-—-Mautic-Community-Handbook-0-1-documentation-02-28-2025_03_31_PM](https://github.com/user-attachments/assets/cff031b6-7f34-4d2e-b41b-3f77e461f23d)

LGTM! 🚀

2025-02-28 15:51 UTC, merged