Google summer of code
mautic/mautic-community-handbook pull request #239
Opened 2024-10-21 22:53 UTC by Iqmaa

Fixes #228 subsection Google Summer of Code. Converted the Google summer of Code page to RST following the given guidelines

2024-10-22 01:46 UTC, RCheesley requested changes
Great job on this so far @Iqmaa - I have made some suggestions for you to fix the reported Vale errors.

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +This page contains information about Mautic's participation in Google Summer of Code, often abbreviated to GSoC. Please feel free to contact us via Slack below for clarifications and more information
```suggestion
This page contains information about Mautic's participation in Google Summer of Code, often abbreviated to GSoC. Please feel free to contact the team via Slack below for clarifications and more information.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +What can I do today?
```suggestion
What to get started with today?
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +********************
Also fix the underline ;)

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +If you're interested in working on a mentor-submitted idea, read the :xref:`GSOC project ideas` and about the project and the related technology. Please note this is a rolling document which we maint
```suggestion
If you're interested in working on a mentor-submitted idea, read the :xref:`GSOC project ideas` and about the project and the related technology. Please note this is a rolling submission process which is maintained year-round. There is no need to contact the mentor unless you have a specific question about the project. Don't send an “I'm interested” email or Slack message - please respect their time.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +- Working with your mentor on realistic achievable milestones that provide for regular deliverables and feedback.
```suggestion
- Working with your mentor on realistic achievable milestones that provide for regular deliverable targets and feedback.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +Interested in applying for Google Summer of Code with Mautic? Here is how you do that!
```suggestion
Interested in applying for Google Summer of Code with Mautic? Here is how you do that.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +3. Submit the application/proposal including all requirements in the next section at the Google Summer of Code Site. We **strongly** encourage you to not submit your final PDF until you get feedback
```suggestion
3. Submit the application/proposal including all requirements in the next section at the Google Summer of Code Site. We **strongly** encourage you to not submit your final PDF until you get feedback about the proposal from your mentors.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +Help is available! Share your application in progress and get feedback. The mentors can help verify your understanding of the project and provide guidance on whether your plan is good.
```suggestion
Help is available. Share your application in progress and get feedback. The mentors can help verify your understanding of the project and provide guidance on whether your plan is good.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +  - Do you have any past involvement with the Mautic Project or another Open Source project as a contributor? What kind of contributions have you made (code and non-code)? Please share any public con
```suggestion
  - Do you have any past involvement with the Mautic Project or another Open Source project as a contributor? What kind of contributions have you made (code and non-code)? Please share any public contributions you have made (URLs, etc.)
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +  - Do you plan to continue contributing to the Mautic Project after GSoC? If yes, what project(s) are you interested with?
```suggestion
  - Do you plan to continue contributing to the Mautic Project after GSoC? If yes, what projects are you interested with?
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +  - Have you contacted the mentor(s) listed for the project?
```suggestion
  - Have you contacted the mentors listed for the project?
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +- Propose a rough schedule for this project. Ideally you will have regular deliverables throughout the entire period.
```suggestion
- Propose a rough schedule for this project. Ideally you'll have regular deliverable tasks throughout the entire period.
```

2024-10-22 01:46 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +- What are you specific plans from May to September (eg: Exams in university, internships, vacations..etc). We need to know if there are periods of time where you are likely to be unavailable. We are
```suggestion
- What are you specific plans from May to September (for example, exams in university, internships, vacations, etc). We need to know if there are periods of time where you are likely to be unavailable. We are better at accommodating these periods if we know of them in advance.
```

2024-10-25 09:51 UTC, RCheesley requested changes
Just some small changes suggested by Vale - shout if you need any help!

2024-10-25 09:51 UTC, RCheesley commented on docs/contributing/google_summer_of_code.rst
> +If you're interested in working on a mentor-submitted idea, read the :xref:`GSOC project ideas` and about the project and the related technology. Please note this is a rolling submission process whic
```suggestion
If you're interested in working on a mentor-submitted idea, read the :xref:`GSOC project ideas` and about the project and the related technology. Please note this is a rolling submission process which Mautic maintains year-round. There is no need to contact the mentor unless you have a specific question about the project. Don't send an ``“I'm interested”`` email or Slack message - please respect their time.
```

Vale fix

2024-10-25 14:15 UTC, Iqmaa commented
> Just some small changes suggested by Vale - shout if you need any help!

Done,
Thanks @RCheesley !

2024-10-28 13:09 UTC, RCheesley submitted a review, later dismissed
Great job @Iqmaa - this is good to go 🚀

2024-10-28 14:09 UTC, RCheesley commented
This is good to merge now, the other issues causing it to fail are due to #244.

2024-10-28 14:09 UTC, merged