added code of coduct
mautic/mautic-community-handbook pull request #251
Opened 2024-11-05 13:06 UTC by favour-chibueze

2024-11-19 14:58 UTC, RCheesley requested changes
We need to address the failures here by either making the link (e.g. a link file with maito:address@example.com or using Vale off / vale on if it's a necessary phrase). We can also add words which are suggested as a typo to the accept.txt file.

2025-02-20 11:35 UTC, RCheesley submitted a review, later dismissed
Good to go!

2025-02-20 11:39 UTC, merged

2025-03-25 07:04 UTC, favour-chibueze commented
Please, add me to the contributors page. @RCheesley

2025-03-25 09:01 UTC, RCheesley commented
@all-contributors please add @favour-chibueze for docs