Update Leadership team page.md
mautic/mautic-community-handbook pull request #254
Opened 2024-12-02 21:33 UTC by ASHMITA489

2024-12-03 19:04 UTC, RCheesley commented
The build is failing here due to some broken links which need to be updated / excluded - so you can disregard that failing test.

2024-12-04 16:04 UTC, RCheesley requested changes
This is great but please can you add the people stepping down to the Honor Roll below? Thanks!

2024-12-04 16:33 UTC, ASHMITA489 commented
Yes done. Please review it.

2025-01-27 14:45 UTC, RCheesley requested changes
Just a small tweak here! Thank you @ASHMITA489 🚀

2025-01-27 14:45 UTC, RCheesley commented on pages/04.community-leadership/01.current-leadership-team/docs.md
> +| Nico Grienauer          | Community Team Assistant Lead         |  2020               |  2022             |
```suggestion
| Nico Grienauer          | Community Team Assistant Lead         |  2020               |  2024             |
```
Nico stepped down this year, so just a small tweak here.

2025-01-30 02:34 UTC, ASHMITA489 commented on pages/04.community-leadership/01.current-leadership-team/docs.md
> +| Nico Grienauer          | Community Team Assistant Lead         |  2020               |  2022             |
I have committed the changes.

2025-02-28 16:57 UTC, RCheesley approved these changes

2025-02-28 16:57 UTC, merged

2025-03-25 07:02 UTC, favour-chibueze commented
@RCheesley Please, let's add @ASHMITA489 to the contributors page

2025-03-25 08:59 UTC, RCheesley commented
Please do, anyone can do that by using the command @all-contributors add @ASHMITA489 for docs. It then creates a PR which you can merge.

2025-03-25 10:58 UTC, ASHMITA489 commented
Thank you for adding me:)