Update current_leadership_team.rst
mautic/mautic-community-handbook pull request #255
Opened 2024-12-02 21:42 UTC by ASHMITA489

2024-12-03 19:03 UTC, RCheesley commented
The build is failing here due to some broken links which need to be updated / excluded - so you can disregard that failing test.

2024-12-04 16:04 UTC, RCheesley requested changes
This is great, but can you add the folks stepping down to the honor roll below, as well? Thanks!

2024-12-04 16:12 UTC, ASHMITA489 commented
Yes sure

2025-01-27 14:47 UTC, RCheesley requested changes
A few tweaks here. Thanks @ASHMITA489 - in the future you can make one PR to change both files, which makes it easier for fixing stuff.

2025-01-27 14:47 UTC, RCheesley commented on docs/community_leadership/current_leadership_team.rst
> +     - 2022
```suggestion
     - 2024
```

This one needs a tweak, too!

2025-01-27 14:47 UTC, RCheesley commented on docs/community_leadership/current_leadership_team.rst
> +     - 2021
```suggestion
     - 2021
     - 2024
```

2025-01-27 14:47 UTC, RCheesley commented on docs/community_leadership/current_leadership_team.rst
> +     - 2026
```suggestion
     - 2024
```

2025-01-30 02:35 UTC, ASHMITA489 commented on docs/community_leadership/current_leadership_team.rst
> +     - 2026
I have committed the changes.

2025-02-28 17:09 UTC, RCheesley approved these changes
I've fixed the broken table layouts, a couple of Vale issues, updated to Mautic Council from Community Council and put a link to the governance model.

2025-02-28 17:10 UTC, merged