Update outdated branching strategy
mautic/mautic-community-handbook pull request #35
Opened 2021-02-23 17:56 UTC by RCheesley

We have changed the branching strategy but we did not update it here! 🤦‍♀️

2021-02-24 20:09 UTC, dennisameling requested changes
This looks great, just noticed some minor typos which I'll also fix in the original article at https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#choose-the-right-branch!

2021-02-24 20:09 UTC, dennisameling commented on pages/03.community-structure/01.Governance model/01.code-governance/docs.md
> +|3.2.0|❌|✅|✅|
```suggestion
|3.3.0|❌|✅|✅|
```

2021-02-24 20:09 UTC, dennisameling commented on pages/03.community-structure/01.Governance model/01.code-governance/docs.md
> +Mautic follows [Semantic Versioning][semver], which is best illustrated by an example. Let's say we just released a 3.0.0 version of Mautic, the following would apply:
```suggestion
Mautic follows [Semantic Versioning][semver], which is best illustrated by an example. Let's say we just released a 3.2.0 version of Mautic, the following would apply:
```

2021-02-25 11:34 UTC, RCheesley commented
Ignore my comment in the other PR - just read this one!

2021-08-18 11:05 UTC, merged