Refresh, inspired by Mautic Conference 2021
mautic/mautic-community-handbook pull request #51
Opened 2021-06-08 06:44 UTC by ekkeguembel

2021-06-08 06:45 UTC, ekkeguembel commented
Note that this includes a rephrasing of the mission statement as well as now officially mentions the NGO topic.

2021-06-08 19:17 UTC, RCheesley requested changes
A couple of suggestions / points of clarification!

2021-06-08 19:17 UTC, RCheesley commented on pages/08.community-team/chapter.md
> +* Work towards a Mautic NGO (e.g. „Mautic Association“)
```suggestion
```

I am not sure this is on the cards for some time, we said we would review whether there was a need for such an entity annually:

> Therefore, we propose to revisit this discussion in twelve months (September 2020) in the context of the Community Council to determine whether the community is at a point where an NGO would be of benefit.  At this point, if it is determined by the Community Council that an NGO should be established, Acquia will fully support any processes necessary to enable its creation.
_Source: https://www.mautic.org/blog/press/response-to-community-consultation-on-the-governance-model-proposal_

So on that basis I would not feel comfortable with the wording of 'working towards a Mautic NGO' seeing as we have not even established a need for one in the Community Council yet.

Open to your thoughts on this topic.

2021-06-08 19:17 UTC, RCheesley commented on pages/08.community-team/chapter.md
> +* Support funding
```suggestion
* Support fundraising initiatives
```

2021-06-10 12:59 UTC, RCheesley approved these changes

2021-06-10 12:59 UTC, merged