update Education-team
mautic/mautic-community-handbook pull request #58
Opened 2021-08-11 01:45 UTC by fakela

2021-08-11 08:38 UTC, RCheesley commented
Looks good but can we use link macros rather than inline links? Otherwise a great improvement :)

2021-08-12 12:41 UTC, RCheesley requested changes
Just a couple of missing spaces to fix, also I think that we should refer to the user/dev docs as they are known (user documentation/developer documentation) rather than guide as it may confuse some folk?  See what you think :)

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +    * [User Guide][User Guide] Describes key concepts of Mautic and provides instructions for using and contributing to Mautic.
```suggestion
    * [User Documentation][User Documentation] Describes key concepts of Mautic and provides instructions for using and contributing to Mautic.
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +    * [Developer Guide][Developer Guide]details about the Mautic API, Webhooks, themes and plugin development.
```suggestion
    * [Developer Documentation][Developer Documentation] details about the Mautic API, Webhooks, themes and plugin development.
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +     * [The Mautic Style Guide][The Mautic Style Guide]recommends best practices that aims to bring about a consistent style, voice, and tone across all documentation
```suggestion
     * [The Mautic Style Guide][The Mautic Style Guide] recommends best practices that aims to bring about a consistent style, voice, and tone across all documentation
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[User Guide]:<https://docs.mautic.org/en>
```suggestion
[User Documentation]: <https://docs.mautic.org/en>
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[Developer Guide]:<https://developer.mautic.org/>
```suggestion
[Developer Documentation]: <https://developer.mautic.org/>
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[Knowledgebase]:<https://kb.mautic.org>
```suggestion
[Knowledgebase]: <https://kb.mautic.org> 
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[Community Handbook]:<https://contribute.mautic.org/>
```suggestion
[Community Handbook]: <https://contribute.mautic.org/> 
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[Mautic Community Forums]:<https://forum.mautic.org>
```suggestion
[Mautic Community Forums]: <https://forum.mautic.org>
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[The Mautic Style Guide]:<https://docs.mautic.org/en/contributing/style-guide>
```suggestion
[The Mautic Style Guide]: <https://docs.mautic.org/en/contributing/style-guide>
```

2021-08-12 12:41 UTC, RCheesley commented on pages/09.education-team/chapter.md
> +[#t-education]:<https://mautic.slack.com/archives/CQGQ0D4KU>
```suggestion
[#t-education]: <https://mautic.slack.com/archives/CQGQ0D4KU>
```

2021-08-12 18:39 UTC, fakela commented
All changes resolved

2021-08-12 19:17 UTC, RCheesley approved these changes

2021-08-12 19:17 UTC, merged